// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZeByjJUAtUDyZEHb5dW9J0zW53IRSsLg',
    appId: '1:775344918903:web:66da757c1e8edb4e935172',
    messagingSenderId: '775344918903',
    projectId: 'firewall-c6143',
    authDomain: 'firewall-c6143.firebaseapp.com',
    storageBucket: 'firewall-c6143.appspot.com',
    measurementId: 'G-2R6ZBQ4PK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmUlTOZuFbIkBUiRKOK3yZi1kw-XGJpoQ',
    appId: '1:775344918903:android:8bdba156b01b47af935172',
    messagingSenderId: '775344918903',
    projectId: 'firewall-c6143',
    storageBucket: 'firewall-c6143.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC1ZaqUJgKb7CtGWIjxA0UdLTaOiD2kQc',
    appId: '1:775344918903:ios:e564e5d5b1962e36935172',
    messagingSenderId: '775344918903',
    projectId: 'firewall-c6143',
    storageBucket: 'firewall-c6143.appspot.com',
    iosBundleId: 'com.example.googleSolutionChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC1ZaqUJgKb7CtGWIjxA0UdLTaOiD2kQc',
    appId: '1:775344918903:ios:926ac5bf29bbb0dc935172',
    messagingSenderId: '775344918903',
    projectId: 'firewall-c6143',
    storageBucket: 'firewall-c6143.appspot.com',
    iosBundleId: 'com.example.googleSolutionChallenge.RunnerTests',
  );
}
